    /* */
    
    @Library("standardPipeline") _
    
    standardPipeline {
        projectName = "MavenTemplate-global"
        serverDomain = "Project1 Server Domain"
        stevesVar = "Steves var passed from MavenTemplate-global"
        
        //projectName="${env.BUILD_ID}"
    }