/* You can pass any custom vars as shown below to
       uniquely identify the calling project 
       
       */
       
    @Library("standardPipeline") _
    
    standardPipeline {
        projectName = "MavenTemplate-global"
        //serverDomain = "Project1 Server Domain"
        stevesVar = "Steves var passed from global"
    }
    
    /* See global/vars/standardPipeline.groovy for 
       how these interact 
    
    MavenTemplate-global/Jenkinsfile -> global/vars/standardPipeline
    
    */