    /* */
    @Library("standardPipeline") _
    standardPipeline {
        //projectName = "Project1"
        serverDomain = "Project1 Server Domain"
        stevesVar = "Steves var passed form global"
        
        //projectName="${env.BUILD_ID}"
    }