pipeline {
    agent any
  tools {
        maven 'Maven 3.5.2'
        jdk 'Java 8u152'
    }
   
    stages {
        stage('Init') {
           steps {
                             echo 'Init'
           
           
                    script {
                       jobName="MavenTemplate"
                    }
              
              echo "jobName=${jobName}"
           }
        }
        
        
        /* Comment this until Sonar is up and running */
        
        stage('Sonarqube analysis') {
           steps {
              echo 'Sonarqube analysis'
              script {
                 scannerHome = tool 'Sonar';
              }
              echo "scannerHome=${scannerHome}"
               
       
              withSonarQubeEnv('SonarServer') {
                 //sh "${scannerHome}/bin/sonar-scanner"
                  sh 'mvn -f MavenTemplate/ org.sonarsource.scanner.maven:sonar-maven-plugin:3.2:sonar'
              }
              
           }
        }
        
        
        stage('Build') {
            steps {
                echo "888"
                echo 'Building..1'
                echo "Running ${env.BUILD_ID} on ${env.JENKINS_URL}"
                // export JENKINS_MAVEN_AGENT_DISABLED=true
                sh 'mvn -f MavenTemplate/ -B install'
            }
        }
        
        stage('Test') {
            steps {
                echo 'Testing..1'
                sh 'mvn -f MavenTemplate/ -Dmaven.test.failure.ignore=true -B test'
            }
        }
        
        stage('Deploy') {
            steps {
                echo 'Deploying....1'
                echo 'project.name=${project.name}'
                sh 'pwd'
                sh 'cp MavenTemplate/target/MavenTemplate-0.0.1-SNAPSHOT.jar /tmp/MavenTemplate.jar'
            }
        }
        
    }
    
        post {
        always {
            echo "Post-always Updated from github"
        }
        success {
            echo "Post-success"
        }
        failure {
            echo "Post-failure"
        }
    }
    
    
    
}
